server:
  port: 18082


spring:
  # mysql
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false

# redis 유지시간
expire:
  defaultTime: 3600

mybatis:
  mapper-locations: classpath*:mappers/*.xml

