### 회원가입 (sign-up)
POST http://localhost:18082/users/sign-up
Content-Type: application/json

{
  "userId": "sumin6",
  "password": "1234",
  "nickName": "ksm6",
  "isAdmin": true,
  "isWithDraw": false,
  "status": "ADMIN"
}

### 로그인 (sign-in)
POST http://localhost:18082/users/sign-in
Content-Type: application/json

{
  "userId": "sumin5",
  "password": "1234"
}

### 회원정보 조회 (my-info)
GET http://localhost:18082/users/my-info


### 패스워드 변경 (password)
PATCH http://localhost:18082/users/password
Content-Type: application/json

{
  "beforePassword": "12345",
  "afterPassword": "1234"
}

### 로그아웃 (logout)
PUT http://localhost:18082/users/logout

### 아이디 삭제
DELETE http://localhost:18082/users
Content-Type: application/json

{
  "id": "sumin2",
  "password": "12345"
}